name: CI/CD pipeline

env:
  NODE_VERSION: "node:25-alpine"
  DOCKER_IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/calculatrice:latest

on:
  push:
    branches:
      - main
      - deveop

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Build application
        run: |
          npm ci
          npm run build

  run_tests:
    runs-on: ubuntu-latest
    needs: build_app
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Run tests
        shell: bash
        run: |
          npm run test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: Set up docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE_NAME }}

      - name: Run docker image
        shell: bash
        run: docker run ${{ vars.DOCKER_IMAGE_NAME }}

      - name: logout
        if: always()
        run: docker logout
